spring:
  application:
    name: betsettlement
  datasource:
    url: "jdbc:h2:mem:betsettlement;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      default-topic: ${app.kafka.topics.event-outcomes.name}
    listener:
      ack-mode: manual_immediate
    consumer:
      group-id: outcome-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "com.sprotygroup.betsettlement.event,com.sprotygroup.betsettlement.dto"
            value:
              default:
                type: com.sprotygroup.betsettlement.event.EventOutcome
    producer:
      acks: all
      retries: 2147483647
      properties:
        idempotence: true
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        delivery.timeout.ms: 120000

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: bet-settlement-producer-group
    send-message-timeout: 3000
    retry-times-when-send-failed: 2
    max-message-size: 4194304

app:
  kafka:
    topics:
      event-outcomes:
        name: event-outcomes
        partitions: 3
        replicas: 1
        group: outcome-group
      settlement-tasks:
        name: settlement-tasks
        partitions: 64
        replicas: 1
        group: bet-settlement-task-group
  rocketmq:
    topic:
      bet-settlements: bet-settlements
  settlement:
    total-buckets: ${app.kafka.topics.settlement-tasks.partitions}
    task-topic: ${app.kafka.topics.settlement-tasks.name}

server:
  port: 8084

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
